### ISSUE TITLE
Get syncing info always return null

### ISSUE THREAD

**Issue by AsceticBear** [PureStake/moonbeam-docs#160]
![image](https://user-images.githubusercontent.com/11801722/136527490-c7e50a9b-b851-412d-9b2c-e58aed5cee8e.png)

Following https://docs.moonbeam.network/builders/tools/pubsub/#check-if-a-node-is-synchronized-with-the-network query the syncing status, the return result seems empty.

- Test script:

```js
const Web3 = require("web3");
const web3 = new Web3('wss://wss.testnet.moonbeam.network');


web3.eth
  .subscribe("syncing")
  .on("connected", function (subscriptionId) {
    console.log(subscriptionId);
  })
  .on("data", function (log) {
    console.log(log);
  });
```
- Output:

```js
> node test_sync.js                                                                                      ~/w/d/d/tests
0x44546f334c704d6d6e356e4c41727a76
```

**Comment by albertov19** [comment]
Hey @AsceticBear I think this PR fixed the issue: https://github.com/paritytech/frontier/pull/630  - so I'll close this one
