### ISSUE TITLE
Tracing node instructions incorrectly recommend `--execution native`

### ISSUE THREAD

**Issue by JoshOrndorff** [PureStake/moonbeam-docs#191]
See https://docs.moonbeam.network/node-operators/networks/tracing-node/#run-a-tracing-node

We no longer need the native runtime for tracing thanks to some awesome work by Telmo and Jeremy.

Originally reported in https://github.com/PureStake/moonbeam/issues/1060#issuecomment-987958406 (thanks @omryr)

**Comment by albertov19** [comment]
Documentation updated! Thanks :) 

https://docs.moonbeam.network/node-operators/networks/tracing-node/#run-a-tracing-node
