### ISSUE TITLE
AmsterDOT Moonbeam Bounty 2 - Build a DApp that Uses XCM

### ISSUE THREAD

**Issue by themacexpert** [PureStake/moonbeam-docs#295]
_The following Issue is a description of an AmsterDOT Bounty and is not meant to convey an issue with Moonbeam-Docs_

**Description**:
XCM is a foundational new technology of Polkadot that allows heterogeneous blockchains to interoperate and seamlessly transfer value. XCM functionality was enabled on Moonriver by introducing the XC-20 standard, a Substrate-native asset that conforms to ERC-20 standards. xcKSM or KSM migrated from the Kusama Relay Chain, is the first XC-20 to launch on Moonriver and allows KSM to be harnessed in the growing DeFi ecosystem in Moonriver. xcKSM is already tradable on several decentralized exchanges.

XC-20s look and behave like typical [ERC-20s](https://github.com/PureStake/moonbeam/blob/master/precompiles/assets-erc20/ERC20.sol), which means that interacting with them is easy. However, before getting started, you should understand the [fundamentals of how XCM](https://docs.moonbeam.network/builders/xcm/xc20/) works. In this challenge, build a project that harnesses XC-20s on Moonriver. In thinking through your project idea, there are two user scenarios to consider.

At a minimum, your project should address the needs of a user who already has XC-20s. The simplest project for this bounty is a DApp that is compatible with XC-20s. Given that XC-20s behave exactly like ERC-20s, this is a straightforward integration.

A complete project would be one that considers a user who does not yet have XC-20s on Moonriver. This holistic approach would consider a user’s token balances across multiple chains (such as Moonriver and the Kusama relay chain). Sample project ideas include DeFi applications for XC-20s, unified wallets that track balances across chains, and unified XCM block explorers.

**Requirements**:
- Your project should have a front-end (a basic one is fine).
- Your finished project should be deployed to Moonbase Alpha.

**Helpful resources**:
- XCM Overview: https://docs.moonbeam.network/builders/xcm/overview/ 
- Interacting with XC20s: https://docs.moonbeam.network/builders/xcm/xc20/ 
- How to Interact with xcRMRKs: https://youtu.be/G0882jjbohw 
- How to Interact with Cross Chain Assets on Moonriver: https://youtu.be/5hI59Bum4dU 
- Moonbuilder’s Workshop - A Technical Introduction to XCM on Moonbeam: https://youtu.be/5HD5rFBqvQ4
- XC-20s: The New Standard for Cross-Chain Tokens on Dotsama: https://moonbeam.network/blog/introducing-xc-20s-the-new-standard-for-cross-chain-tokens-on-dotsama/ 
- Get XC-20 Tokens on Moonbase Alpha here: https://moonbeam-swap.netlify.app/#/swap
- Moonbeam Discord for DEV Faucet Funds and Technical Support: https://discord.gg/moonbeam

**Judging Criteria**:
Projects will be judged based on the overall quality of the submission, with an emphasis on the user experience.

**Comment by albertov19** [comment]
@themacexpert can this issue be closed now? (same as for the other AmsterDOT related issue)
