### ISSUE TITLE
Add Ankr to Endpoint Providers

### ISSUE THREAD

**Issue by ddocs** [PureStake/moonbeam-docs#300]
I'd love to add our Ankr Moonbeam RPCs to your list of Endpoint Providers. We have a free public one here: [https://www.ankr.com/protocol/public/moonbeam/](https://www.ankr.com/protocol/public/moonbeam/) that requires zero sign up, and you can just get started straight away. (We've also got a premium plan that allows you to sign up to all our multi-chain RPCs).

**Comment by albertov19** [comment]
Hey @ddocs ! Will you be adding Moonriver as well? Thanks in advance

**Comment by ddocs** [comment]
Hey @albertov19. Would you be able to explain what Moonriver is. Is it a testnet?

**Comment by ddocs** [comment]
I see it is equivalent to kusama for polkadot. We are gradually rolling out testnets and Moonriver is one that will be rolled out. It is not in the current pipeline.

**Comment by eshaben** [comment]
Moonriver isn't really a testnet in the traditional sense. It has real economic value tied to it. Similarly to how Kusama is not really a true testnet. But yes, similar to how Moonbeam is our mainnet deployment on Polkadot, Moonriver is our mainnet deployment on Kusama. Our testnet is Moonbase Alpha.
