### ISSUE TITLE
EvmError with Forge for any call to xcDOT on Moonbeam

### ISSUE THREAD

**Issue by vminkov** [PureStake/moonbeam-docs#384]
Every call to the `xcDOT` contract fails when using forge, here is an example

```
interface StandardErc20 {
    function approve(address to, uint256 amount) external returns (bool);
}

contract SimpleXcDotTest {
    function testDotApprove() public {
        address xcDotAddress = 0xFfFFfFff1FcaCBd218EDc0EbA20Fc2308C778080;

        StandardErc20 xcDot = StandardErc20(xcDotAddress);

        // this fails
        xcDot.approve(address(2), 2e18);
    }
}
```

```
Running 1 test for contracts/test/sol:SimpleXcDotTest.sol:SimpleXcDotTest
[FAIL. Reason: EvmError: Revert] testDotApprove() (gas: 2879)
Traces:
  [2879] SimpleXcDotTest::testDotApprove() 
    ├─ [6] 0xffff…8080::095ea7b3(00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000001bc16d674ec80000) 
    │   └─ ← ()
    └─ ← "EvmError: Revert"

Test result: FAILED. 0 passed; 1 failed; finished in 1.39s

Failing tests:
Encountered 1 failing test in contracts/test/sol:SimpleXcDotTest.sol:SimpleXcDotTest
[FAIL. Reason: EvmError: Revert] testDotApprove() (gas: 2879)
```

**Comment by albertov19** [comment]
Hey @vminkov are you testing against Moonbase Alpha? Moonbeam? Can you provide a bit more of context? 

Thanks in advance

**Comment by vminkov** [comment]
> Hey @vminkov are you testing against Moonbase Alpha? Moonbeam? I'm guessing Moonbeam as you are referring to `xcDOT`, but just wanted to confirm. Can you provide a bit more of context?
> 
> Thanks in advance
Hey there, @albertov19 

I am testing against Moonbeam with this command:
`forge test --fork-url https://rpc.api.moonbeam.network -vvvv --match-test testDotSwap`

**Comment by albertov19** [comment]
I'm almost certain that Mainnet Forking is not compatible with our precompile contracts. We'll do some internal testing and get back to you.

**Comment by albertov19** [comment]
> > Hey @vminkov are you testing against Moonbase Alpha? Moonbeam? I'm guessing Moonbeam as you are referring to `xcDOT`, but just wanted to confirm. Can you provide a bit more of context?
> > Thanks in advance
> 
> Hey there, @albertov19
> 
> I am testing against Moonbeam with this command: `forge test --fork-url https://rpc.api.moonbeam.network -vvvv --match-test testDotSwap`

I'm almost certain that Mainnet Forking is not compatible with our precompile contracts. We'll do some internal testing and get back to you.
