### ISSUE TITLE
{target=_blank) shown on foundry page

### ISSUE THREAD

**Issue by timbrinded** [PureStake/moonbeam-docs#439]
On the foundry page: https://docs.moonbeam.network/builders/build/eth-api/dev-env/foundry/#creating-a-foundry-project

we should `{target=_blank)` in the main body text for some reason:
![image](https://user-images.githubusercontent.com/79199034/196496745-87c8be17-37ae-4c63-9dfe-3d19df985123.png)

-----------------------
Looks to be a bad brace, it's a `)` erroneously.

**Comment by eshaben** [comment]
Addressed in https://github.com/PureStake/moonbeam-docs/pull/440

**Comment by eshaben** [comment]
Thanks @timbrinded 🙂
