### ISSUE TITLE
Add Getblock public and dedicated endpoints

### ISSUE THREAD

**Issue by JoGetBlock** [PureStake/moonbeam-docs#443]
GetBlock is a service that provides instant API access to more than 40 leading blockchains, including Moonbeam and Moonriver available for shared and dedicated nodes.
GetBlock offers an option: dedicated [Moonbeam](https://getblock.io/dedicated-nodes/glmr/) and [Moonriver](https://getblock.io/dedicated-nodes/movr/) nodes and shared nodes for [Moonbeam](https://getblock.io/nodes/glmr/) and [Moonriver](https://getblock.io/nodes/movr/).

Get started with GetBlock

[Register an account](https://account.getblock.io/)

<img width="1191" alt="Register an account " src="https://user-images.githubusercontent.com/111500252/196967055-1aeae866-4151-455c-9ee3-62b141dbfde7.png">

Open GetBlock Dashboard and Set you API Key 
Generate your endpoint

<img width="1191" alt="GetBlock Dashboard" src="https://user-images.githubusercontent.com/111500252/196967338-acdb04f2-18a5-4a94-9c17-e43717ca9d62.png">

Search for the necessary blockchain then choose the network, proceed by clicking “create” and there it is!

<img width="1174" alt="Moonbeam" src="https://user-images.githubusercontent.com/111500252/196967662-348faef4-e9d5-45a0-942a-8c7ef83f0d38.png">

<img width="1174" alt="Endpoint created" src="https://user-images.githubusercontent.com/111500252/196968173-40ba857f-f29a-421e-a096-9e217bc06535.png">

**Comment by albertov19** [comment]
@JoGetBlock I'll close the issue as there is already a PR waiting to be merged. Thanks!
