### ISSUE TITLE
Chopsticks docs suggestion

### ISSUE THREAD

**Issue by ermalkaleci** [PureStake/moonbeam-docs#578]
You don't need to run polkadot-ui to connect to chopsticks. polkadot.js.org/apps/ will do

**Comment by albertov19** [comment]
@ermalkaleci thanks for the suggestion. @jboetticher we can add this, thanks!

**Comment by jboetticher** [comment]
https://github.com/PureStake/moonbeam-docs/commit/2aefd3e719645375098085aecfc51cdafcc38583
