### ISSUE TITLE
[Feedback] Send Transactions & Deploy Contracts with Web3.js - /builders/build/eth-api/libraries/web3js/

### ISSUE THREAD

**Issue by CasiniNift** [PureStake/moonbeam-docs#672]
Hello, 

I am doing the Moonbuilder Academy course. I am in lesson 4. 
When the video gets to time slot 3:02, a document is opened with the keys for the example. Where can I find that document?

Since those are just test accounts, the keys should be written in the documentation and easy to find.

**Comment by eshaben** [comment]
@CasiniNift hey! thanks for the feedback. I'll see if we can add the development accounts somewhere in the Moonbuilders Academy UI or at least link back to the specific section on our docs site, but they are listed on our docs here: https://docs.moonbeam.network/builders/get-started/networks/moonbeam-dev/#pre-funded-development-accounts. You can expand the "Development account addresses and private keys" note. 

Out of curiosity, where did you look in the documentation? We can probably add the accounts there too! Thanks again for the feedback, we appreciate it! 🙂

**Comment by Niftgen-main** [comment]
Thank you @eshaben for the link!
I think that there should perhaps be a link for Prefunded Development Accounts on all of the sections ?

The documentation I looked at where the links provided bellow the videos.

**Comment by CasiniNift** [comment]
Thank you @eshaben  for the link! I think that there should perhaps be a link for Prefunded Development Accounts on all of the sections ?
The documentation I looked at where the links provided bellow the videos.

**Comment by eshaben** [comment]
closing this as we've added information on the development accounts and keys to the lesson!
