### ISSUE TITLE
Instructions should only check one mapping

### ISSUE THREAD

**Issue by JoshOrndorff** [PureStake/moonbeam-docs#95]
The instructions at https://docs.moonbeam.network/node-operators/networks/collator/#checking-the-mappings show users how to read the entire set of mappings. When the set of mappings grows large this is expensive for the node to lookup and also hard for the user to read.

Rather, they should include their own author Id as a parameter an only look up their own mapping.

**Comment by albertov19** [comment]
Once the list grows larger I'll just change the tutorial make sure people just look for their own author id

**Comment by albertov19** [comment]
This was fixed already :) -  https://docs.moonbeam.network/node-operators/networks/collator/#checking-the-mappings
